### ISSUE TITLE
Unable to use craft.agnosticfetch.one, but one() is ok

### ISSUE THREAD

**Issue by bossanova808** [marionnewlevant/craft3-agnostic_fetch#5]
So I a get an error with this:

`{% set logoImageBigOriginal = craft.agnosticfetch.one(randomEntry.masterImage) %}`

`Calling unknown method: craft\web\twig\variables\CraftVariable::agnosticfetch()`

Plugin is definitely installed and enabled.   I can get past the error by changing it to:

`{% set logoImageBigOriginal = one(randomEntry.masterImage) %}`

...I can't for sure tell if it is actually working, though, as so much other stuff is broken, but it gets me past the twig error at least.

Any ideas?

(I've used mneager a lot in my Craft 2 site without issues for the last couple of years)

**Comment by marionnewlevant** [comment]
Thank you for the fix! Sorry it took me so long to spot the issue here in github.
